### ISSUE TITLE
VideoStatusIngest has no attribute 'receivedParts'

### ISSUE THREAD

**Issue by ndkv** [apivideo/api.video-python-client#48]
Hello, 

I get a `VideoStatusIngest has no attribute 'receivedParts' at ['received_data']['ingest']['recievedParts']` error when I call `VideosApi.get_status()` as 

```python
 with apivideo.AuthenticatedApiClient('<api_key>') as client:
        api = videos_api.VideosApi(client)
     
        status = api.get_status('<video_id>')
```

Fetching the status of this video from https://docs.api.video/reference/get-video-status using `<video_id>` works: the response contains the `receivedParts` key, see below. 

![Screenshot 2022-03-21 141621](https://user-images.githubusercontent.com/778666/159268712-4bd9b22a-07fa-4e0b-83c5-a280b245958a.png)

**Comment by olivierapivideo** [comment]
Simeon,

A new release of the client has been deployed on Pypi (v. 1.2.3). It contains a fix for the problem you reported. Please feel free to reopen an issue if you are still experiencing problems.

Best regards

**Comment by ndkv** [comment]
Awesome, thank you for the quick fix!
